# Generated by Django 3.2.9 on 2021-12-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cokie',
            name='body',
            field=models.TextField(max_length=800),
        ),
    ]
