# Generated by Django 3.2.9 on 2021-12-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooki', '0002_alter_cokie_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cokie',
            name='image',
            field=models.ImageField(max_length=300, upload_to=''),
        ),
    ]
