# Generated by Django 3.2.9 on 2021-12-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooki', '0004_alter_cokie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cokie',
            name='showed',
            field=models.CharField(max_length=40),
        ),
    ]
