# Generated by Django 3.2.9 on 2021-12-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooki', '0005_alter_cokie_showed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cokie',
            name='body',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='cokie',
            name='image',
            field=models.CharField(max_length=300),
        ),
    ]
