# Generated by Django 3.2.9 on 2021-12-05 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooki', '0006_auto_20211205_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cokie',
            old_name='name',
            new_name='namef',
        ),
    ]
