# Generated by Django 3.2.9 on 2021-12-05 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooki', '0007_rename_name_cokie_namef'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cokie',
            old_name='namef',
            new_name='name',
        ),
    ]
